name: Update submodule

on:
  schedule:
    - cron: '0 0 * * *'  # Update submodule daily
  
  workflow_dispatch:  # Manually trigger workflow

jobs:
  update_submodule:
    name: Update submodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update submodule
        run: git submodule update --init --recursive --remote

      - name: Commit submodule changes
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update submodule"